import {
  User, Skull, ScrollText, Building2, Wand2, Globe, Map, Search,
  Swords, Crown, ShoppingCart, Heart, Dog, Zap,
  Mountain, Flag, Church, Palette, CalendarDays, BookOpen,
  Target, Route, Eye, MessageCircle, Compass,
  Gem, FlaskConical, Shield, Package, Store,
  MapPin, Castle, Grid3X3,
  Dice6, Type, Cloud, FileText, Puzzle, PartyPopper,
  Brain, Layers, CheckCircle, AlertTriangle, FileStack, RefreshCw,
  LucideIcon,
} from "lucide-react";

export interface FieldSchema {
  key: string;
  label: string;
  type: 'string' | 'text' | 'select' | 'array' | 'boolean' | 'number';
  options?: string[];
  placeholder?: string;
}

export interface BetaTool {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  description: string;
  icon: LucideIcon;
  assetType: string;
  status: 'active' | 'coming_soon';
  fields: FieldSchema[];
  examplePrompts: string[];
  outputHints?: string[];
}

export interface ToolCategory {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  { id: 'characters', label: 'Characters', icon: User, description: 'NPCs, villains, merchants, and more' },
  { id: 'creatures', label: 'Creatures', icon: Skull, description: 'Monsters, bosses, and beasts' },
  { id: 'world', label: 'World', icon: Globe, description: 'Settlements, regions, factions' },
  { id: 'story', label: 'Story', icon: ScrollText, description: 'Quests, plot arcs, mysteries' },
  { id: 'items', label: 'Items', icon: Wand2, description: 'Magic items, potions, loot' },
  { id: 'maps', label: 'Maps & Visuals', icon: Map, description: 'Battle maps, dungeons, portraits' },
  { id: 'utilities', label: 'Utilities', icon: Dice6, description: 'Name generators, tables, puzzles' },
  { id: 'smart', label: 'Smart Tools', icon: Brain, description: 'Lore detection, consistency checks' },
];

export const BETA_TOOLS: BetaTool[] = [
  // ===== CHARACTERS =====
  {
    id: 'npc-generator',
    name: 'NPC Generator',
    category: 'characters',
    categoryLabel: 'Characters',
    description: 'Generate fully-fleshed NPCs with personality, goals, secrets, and plot hooks.',
    icon: User,
    assetType: 'npc',
    status: 'active',
    fields: [
      { key: 'name', label: 'Name', type: 'string', placeholder: 'Leave blank for AI to choose' },
      { key: 'role', label: 'Role/Occupation', type: 'string', placeholder: 'e.g. Tavern keeper, Court wizard' },
      { key: 'species', label: 'Species', type: 'string', placeholder: 'e.g. Human, Elf, Tiefling' },
      { key: 'alignment', label: 'Alignment', type: 'select', options: ['Lawful Good', 'Neutral Good', 'Chaotic Good', 'Lawful Neutral', 'True Neutral', 'Chaotic Neutral', 'Lawful Evil', 'Neutral Evil', 'Chaotic Evil'] },
      { key: 'personality_trait', label: 'Key Personality Trait', type: 'string', placeholder: 'e.g. Paranoid, jovial, secretive' },
    ],
    examplePrompts: [
      'A mysterious fortune teller who knows more than she should',
      'A grizzled blacksmith with a hidden past as an adventurer',
      'A cheerful halfling innkeeper who runs a secret smuggling ring',
      'A noble diplomat hiding a dark secret about the royal family',
    ],
    outputHints: ['name', 'personality', 'goals', 'secrets', 'faction ties'],
  },
  {
    id: 'villain-generator',
    name: 'Villain Generator',
    category: 'characters',
    categoryLabel: 'Characters',
    description: 'Create memorable antagonists with motivations and schemes.',
    icon: Crown,
    assetType: 'npc',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
    outputHints: [],
  },
  {
    id: 'merchant-generator',
    name: 'Merchant Generator',
    category: 'characters',
    categoryLabel: 'Characters',
    description: 'Build shopkeepers with inventory, personality, and trade secrets.',
    icon: ShoppingCart,
    assetType: 'npc',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'noble-generator',
    name: 'Noble / Leader Generator',
    category: 'characters',
    categoryLabel: 'Characters',
    description: 'Generate political figures, rulers, and faction leaders.',
    icon: Crown,
    assetType: 'npc',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'companion-generator',
    name: 'Companion Generator',
    category: 'characters',
    categoryLabel: 'Characters',
    description: 'Create followers and sidekicks for the party.',
    icon: Heart,
    assetType: 'npc',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'citizen-generator',
    name: 'Random Citizen',
    category: 'characters',
    categoryLabel: 'Characters',
    description: 'Quick random citizens for background population.',
    icon: User,
    assetType: 'npc',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== CREATURES =====
  {
    id: 'monster-generator',
    name: 'Monster Generator',
    category: 'creatures',
    categoryLabel: 'Creatures',
    description: 'Design unique monsters with abilities, tactics, lore, and stat blocks.',
    icon: Skull,
    assetType: 'monster',
    status: 'active',
    fields: [
      { key: 'name', label: 'Name', type: 'string', placeholder: 'Leave blank for AI to choose' },
      { key: 'creature_type', label: 'Type', type: 'select', options: ['Aberration', 'Beast', 'Celestial', 'Construct', 'Dragon', 'Elemental', 'Fey', 'Fiend', 'Giant', 'Humanoid', 'Monstrosity', 'Ooze', 'Plant', 'Undead'] },
      { key: 'challenge_rating', label: 'Challenge Rating', type: 'string', placeholder: 'e.g. 1/4, 5, 15' },
      { key: 'size', label: 'Size', type: 'select', options: ['Tiny', 'Small', 'Medium', 'Large', 'Huge', 'Gargantuan'] },
      { key: 'environment', label: 'Environment', type: 'string', placeholder: 'e.g. Underdark, forest, coastal' },
    ],
    examplePrompts: [
      'A terrifying undead knight that commands a battalion of skeletons',
      'A mischievous fey creature that steals memories',
      'An ancient construct guardian of a forgotten temple',
      'A swamp-dwelling aberration that mimics voices of loved ones',
    ],
    outputHints: ['stat block', 'abilities', 'tactics', 'habitat', 'lore'],
  },
  {
    id: 'boss-generator',
    name: 'Boss Generator',
    category: 'creatures',
    categoryLabel: 'Creatures',
    description: 'Epic boss encounters with legendary actions and lair effects.',
    icon: Swords,
    assetType: 'monster',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'beast-generator',
    name: 'Beast / Mount Generator',
    category: 'creatures',
    categoryLabel: 'Creatures',
    description: 'Beasts, mounts, and animal companions.',
    icon: Dog,
    assetType: 'monster',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'ability-generator',
    name: 'Monster Ability Generator',
    category: 'creatures',
    categoryLabel: 'Creatures',
    description: 'Unique abilities and actions for existing creatures.',
    icon: Zap,
    assetType: 'monster',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== WORLD =====
  {
    id: 'settlement-generator',
    name: 'Settlement Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Generate towns, cities, and villages with NPCs, economy, and atmosphere.',
    icon: Building2,
    assetType: 'settlement',
    status: 'active',
    fields: [
      { key: 'name', label: 'Name', type: 'string', placeholder: 'Leave blank for AI to choose' },
      { key: 'settlement_type', label: 'Type', type: 'select', options: ['Hamlet', 'Village', 'Town', 'City', 'Metropolis', 'Outpost', 'Fortress', 'Port'] },
      { key: 'population', label: 'Population', type: 'string', placeholder: 'e.g. ~500, thousands' },
      { key: 'primary_industry', label: 'Primary Industry', type: 'string', placeholder: 'e.g. Mining, fishing, trade' },
      { key: 'atmosphere', label: 'Atmosphere', type: 'string', placeholder: 'e.g. Bustling, eerie, war-torn' },
    ],
    examplePrompts: [
      'A floating sky-city connected by bridges between cloud-topped pillars',
      'A grim mining town where workers are mysteriously disappearing',
      'A vibrant coastal trading port ruled by a council of merchant guilds',
      'A hidden elven settlement deep in an ancient forest',
    ],
    outputHints: ['NPCs', 'economy', 'atmosphere', 'plot hooks'],
  },
  {
    id: 'region-generator',
    name: 'Region Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Create regions with geography, cultures, and conflicts.',
    icon: Mountain,
    assetType: 'settlement',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'faction-generator',
    name: 'Faction Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Build organizations with goals, hierarchy, and intrigue.',
    icon: Flag,
    assetType: 'faction',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'religion-generator',
    name: 'Religion / Deity Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Generate religions, pantheons, and divine beings.',
    icon: Church,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'culture-generator',
    name: 'Culture Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Create unique cultures with customs, art, and traditions.',
    icon: Palette,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'history-generator',
    name: 'Historical Event Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Generate pivotal moments in your world\'s history.',
    icon: BookOpen,
    assetType: 'world_event',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'calendar-generator',
    name: 'Calendar / Holiday Generator',
    category: 'world',
    categoryLabel: 'World',
    description: 'Create festivals, holidays, and calendar systems.',
    icon: CalendarDays,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== STORY =====
  {
    id: 'quest-generator',
    name: 'Quest Generator',
    category: 'story',
    categoryLabel: 'Story',
    description: 'Create quests with objectives, complications, twists, and rewards.',
    icon: ScrollText,
    assetType: 'quest',
    status: 'active',
    fields: [
      { key: 'title', label: 'Title', type: 'string', placeholder: 'Leave blank for AI to choose' },
      { key: 'quest_type', label: 'Type', type: 'select', options: ['Main Quest', 'Side Quest', 'Fetch Quest', 'Escort', 'Investigation', 'Dungeon Crawl', 'Political Intrigue', 'Rescue', 'Defense', 'Heist'] },
      { key: 'difficulty', label: 'Difficulty', type: 'select', options: ['Easy', 'Medium', 'Hard', 'Deadly'] },
      { key: 'setting', label: 'Setting/Location', type: 'string', placeholder: 'e.g. Haunted forest, underground ruins' },
      { key: 'hook', label: 'Initial Hook', type: 'string', placeholder: 'How do players learn of this quest?' },
    ],
    examplePrompts: [
      'A missing persons investigation that leads to a cult ritual',
      'A race against time to deliver an antidote across dangerous territory',
      'A heist to steal back a sacred relic from a corrupt noble',
      'An escort mission through monster-infested mountain passes',
    ],
    outputHints: ['objectives', 'complications', 'twists', 'rewards'],
  },
  {
    id: 'side-quest-generator',
    name: 'Side Quest Generator',
    category: 'story',
    categoryLabel: 'Story',
    description: 'Quick side quests for variety and world-building.',
    icon: Target,
    assetType: 'quest',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'plot-arc-generator',
    name: 'Plot Arc Generator',
    category: 'story',
    categoryLabel: 'Story',
    description: 'Multi-session story arcs with rising tension.',
    icon: Route,
    assetType: 'quest',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'mystery-generator',
    name: 'Mystery Generator',
    category: 'story',
    categoryLabel: 'Story',
    description: 'Whodunits and investigation scenarios with clues.',
    icon: Eye,
    assetType: 'quest',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'rumor-generator',
    name: 'Rumor Generator',
    category: 'story',
    categoryLabel: 'Story',
    description: 'Tavern gossip, street whispers, and false leads.',
    icon: MessageCircle,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'travel-event-generator',
    name: 'Travel Event Generator',
    category: 'story',
    categoryLabel: 'Story',
    description: 'Random encounters and events for overland travel.',
    icon: Compass,
    assetType: 'world_event',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== ITEMS =====
  {
    id: 'magic-item-generator',
    name: 'Magic Item Generator',
    category: 'items',
    categoryLabel: 'Items',
    description: 'Create unique magic items with lore, properties, and quirks.',
    icon: Wand2,
    assetType: 'magic_item',
    status: 'active',
    fields: [
      { key: 'name', label: 'Name', type: 'string', placeholder: 'Leave blank for AI to choose' },
      { key: 'item_type', label: 'Item Type', type: 'select', options: ['Weapon', 'Armor', 'Ring', 'Wand', 'Staff', 'Amulet', 'Cloak', 'Boots', 'Potion', 'Scroll', 'Wondrous Item', 'Other'] },
      { key: 'rarity', label: 'Rarity', type: 'select', options: ['Common', 'Uncommon', 'Rare', 'Very Rare', 'Legendary', 'Artifact'] },
      { key: 'attunement', label: 'Requires Attunement', type: 'boolean' },
      { key: 'theme', label: 'Theme/Element', type: 'string', placeholder: 'e.g. Fire, shadow, nature, time' },
    ],
    examplePrompts: [
      'A sentient sword that whispers battle strategies but demands blood sacrifices',
      'A cloak that lets you step between shadows but slowly corrupts the wearer',
      'A humble-looking compass that points toward the nearest source of danger',
      'An ancient ring that grants invisibility but attracts undead attention',
    ],
    outputHints: ['properties', 'lore', 'quirks', 'attunement'],
  },
  {
    id: 'artifact-generator',
    name: 'Artifact Generator',
    category: 'items',
    categoryLabel: 'Items',
    description: 'World-shaping artifacts with legendary powers.',
    icon: Gem,
    assetType: 'magic_item',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'potion-generator',
    name: 'Potion / Poison Generator',
    category: 'items',
    categoryLabel: 'Items',
    description: 'Brews and toxins with effects and side effects.',
    icon: FlaskConical,
    assetType: 'magic_item',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'weapon-generator',
    name: 'Weapon / Armor Generator',
    category: 'items',
    categoryLabel: 'Items',
    description: 'Custom weapons and armor with special properties.',
    icon: Shield,
    assetType: 'magic_item',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'loot-table-generator',
    name: 'Loot Table Generator',
    category: 'items',
    categoryLabel: 'Items',
    description: 'Random loot tables for encounters and dungeons.',
    icon: Package,
    assetType: 'magic_item',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'shop-inventory-generator',
    name: 'Shop Inventory Generator',
    category: 'items',
    categoryLabel: 'Items',
    description: 'Stock up a merchant\'s shop with themed inventory.',
    icon: Store,
    assetType: 'magic_item',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== MAPS & VISUALS =====
  {
    id: 'battle-map-generator',
    name: 'Battle Map Generator',
    category: 'maps',
    categoryLabel: 'Maps & Visuals',
    description: 'Generate tactical battle map descriptions with terrain and cover positions.',
    icon: Grid3X3,
    assetType: 'battle_map',
    status: 'active',
    fields: [
      { key: 'name', label: 'Map Name', type: 'string', placeholder: 'e.g. Ruined Temple Entrance' },
      { key: 'layout_type', label: 'Grid Type', type: 'select', options: ['Square Grid', 'Hex Grid'] },
      { key: 'environment', label: 'Environment', type: 'select', options: ['Indoor', 'Outdoor', 'Underground', 'Underwater', 'Aerial'] },
      { key: 'biome', label: 'Biome/Theme', type: 'string', placeholder: 'e.g. Forest, desert, dungeon, ruin' },
      { key: 'map_size', label: 'Map Size', type: 'select', options: ['Small (20x20)', 'Medium (30x30)', 'Large (40x40)', 'Huge (50x50)'] },
    ],
    examplePrompts: [
      'A narrow canyon ambush with high ground on both sides',
      'A crumbling bridge over a lava river inside a volcano',
      'A dense forest clearing with ancient standing stones',
      'A multi-level tavern with breakable furniture and a secret basement',
    ],
  },
  {
    id: 'dungeon-generator',
    name: 'Dungeon Layout Generator',
    category: 'maps',
    categoryLabel: 'Maps & Visuals',
    description: 'Room-by-room dungeon layouts with encounters.',
    icon: MapPin,
    assetType: 'battle_map',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'settlement-map-generator',
    name: 'Settlement Map Generator',
    category: 'maps',
    categoryLabel: 'Maps & Visuals',
    description: 'Town and city layout descriptions.',
    icon: Castle,
    assetType: 'battle_map',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'world-map-generator',
    name: 'World Map Generator',
    category: 'maps',
    categoryLabel: 'Maps & Visuals',
    description: 'Continental and regional map concepts.',
    icon: Globe,
    assetType: 'battle_map',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'portrait-generator',
    name: 'Portrait / Artwork Generator',
    category: 'maps',
    categoryLabel: 'Maps & Visuals',
    description: 'Character portraits and asset artwork concepts.',
    icon: Palette,
    assetType: 'artwork',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== UTILITIES =====
  {
    id: 'random-table-generator',
    name: 'Random Table Generator',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Custom d100, d20, and other random tables.',
    icon: Dice6,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'name-generator',
    name: 'Name Generator',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Names for NPCs, locations, items, and factions.',
    icon: Type,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'weather-generator',
    name: 'Weather Generator',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Dynamic weather patterns and atmospheric effects.',
    icon: Cloud,
    assetType: 'world_event',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'handout-generator',
    name: 'Handout / Letter Generator',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'In-world documents, letters, and journal entries.',
    icon: FileText,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'puzzle-generator',
    name: 'Puzzle / Trap Generator',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Riddles, puzzles, and trap designs for dungeons.',
    icon: Puzzle,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'festival-generator',
    name: 'Festival / Event Generator',
    category: 'utilities',
    categoryLabel: 'Utilities',
    description: 'Town festivals, tournaments, and social events.',
    icon: PartyPopper,
    assetType: 'world_event',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },

  // ===== SMART TOOLS =====
  {
    id: 'world-event-generator',
    name: 'World Event Generator',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Generate political upheavals, natural disasters, faction conflicts, and more.',
    icon: Globe,
    assetType: 'world_event',
    status: 'active',
    fields: [
      { key: 'name', label: 'Event Name', type: 'string', placeholder: 'Leave blank for AI to choose' },
      { key: 'event_category', label: 'Category', type: 'select', options: ['Political', 'Economic', 'Magical Anomaly', 'Religious', 'Criminal', 'Military Conflict', 'Monster Migration', 'Natural Disaster', 'Faction Development', 'Personal'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['Minor', 'Moderate', 'Major', 'Catastrophic'] },
      { key: 'region', label: 'Affected Region', type: 'string', placeholder: 'e.g. The Northern Reaches' },
      { key: 'factions_involved', label: 'Factions Involved', type: 'string', placeholder: 'e.g. The Iron Crown, The Merchant Guild' },
    ],
    examplePrompts: [
      'A plague sweeps through the capital, and the temples can\'t keep up',
      'Two rival factions declare open war in the streets',
      'A magical anomaly causes wild magic surges across the region',
      'A massive dragon migrates into settled territory seeking a new lair',
    ],
  },
  {
    id: 'missing-lore-detector',
    name: 'Missing Lore Detector',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Scan your campaign for incomplete assets, missing connections, and lore gaps.',
    icon: Search,
    assetType: 'lore_gap',
    status: 'active',
    fields: [],
    examplePrompts: [
      'Scan all NPCs for missing goals or locations',
      'Find factions without clear leadership or enemies',
      'Check quests for missing rewards or unclear objectives',
      'Find locations with minimal descriptions',
    ],
  },
  {
    id: 'lore-expansion',
    name: 'Lore Expansion Tool',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Enrich existing assets with lore-consistent additions.',
    icon: Layers,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'canon-checker',
    name: 'Canon Consistency Checker',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Check for contradictions across your campaign canon.',
    icon: CheckCircle,
    assetType: 'lore_gap',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'campaign-gap-finder',
    name: 'Campaign Gap Finder',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Identify underdeveloped areas of your campaign.',
    icon: AlertTriangle,
    assetType: 'lore_gap',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'auto-shell-builder',
    name: 'Auto-Shell Builder',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Create asset stubs from your session notes.',
    icon: FileStack,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
  {
    id: 'lore-sync',
    name: 'Mass Lore Update',
    category: 'smart',
    categoryLabel: 'Smart Tools',
    description: 'Apply world events across multiple assets at once.',
    icon: RefreshCw,
    assetType: 'lore',
    status: 'coming_soon',
    fields: [],
    examplePrompts: [],
  },
];

export const HERO_TOOLS = BETA_TOOLS.filter(t => t.status === 'active');

export function getToolById(id: string): BetaTool | undefined {
  return BETA_TOOLS.find(t => t.id === id);
}

export function getToolsByCategory(categoryId: string): BetaTool[] {
  return BETA_TOOLS.filter(t => t.category === categoryId);
}

export const ASSET_TYPE_LABELS: Record<string, string> = {
  npc: 'NPC',
  monster: 'Monster',
  quest: 'Quest',
  settlement: 'Settlement',
  magic_item: 'Magic Item',
  world_event: 'World Event',
  battle_map: 'Battle Map',
  lore_gap: 'Lore Gap',
  faction: 'Faction',
  lore: 'Lore',
  artwork: 'Artwork',
};

export const STATUS_LABELS: Record<string, string> = {
  draft: 'Draft',
  standalone: 'Standalone',
  canon_ready: 'Canon Ready',
  imported: 'Imported',
  imported_adapted: 'Adapted',
};
