-- Insert some starter SRD monsters
INSERT INTO public.monster_catalog (name, type, size, alignment, cr, ac, hp_avg, hp_formula, speed, abilities, saves, skills, senses, languages, immunities, resistances, vulnerabilities, traits, actions, proficiency_bonus) VALUES

-- CR 1/8
('Goblin', 'humanoid', 'small', 'neutral evil', 0.125, 15, 7, '2d6', 
'{"walk": 30}',
'{"str": 8, "dex": 14, "con": 10, "int": 10, "wis": 8, "cha": 8}',
'{}',
'{"stealth": 6}',
'{"darkvision": 60}',
'Common, Goblin',
'[]', '[]', '[]',
'[{"name": "Nimble Escape", "description": "The goblin can take the Disengage or Hide action as a bonus action on each of its turns."}]',
'[{"name": "Scimitar", "description": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage."}, {"name": "Shortbow", "description": "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage."}]',
2),

-- CR 1/4
('Wolf', 'beast', 'medium', 'unaligned', 0.25, 13, 11, '2d8+2',
'{"walk": 40}',
'{"str": 12, "dex": 15, "con": 12, "int": 3, "wis": 12, "cha": 6}',
'{}',
'{"perception": 3, "stealth": 4}',
'{}',
'—',
'[]', '[]', '[]',
'[{"name": "Keen Hearing and Smell", "description": "The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell."}, {"name": "Pack Tactics", "description": "The wolf has advantage on attack rolls against a creature if at least one of the wolf''s allies is within 5 feet of the creature and the ally isn''t incapacitated."}]',
'[{"name": "Bite", "description": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone."}]',
2),

-- CR 1/2
('Orc', 'humanoid', 'medium', 'chaotic evil', 0.5, 13, 15, '2d8+6',
'{"walk": 30}',
'{"str": 16, "dex": 12, "con": 16, "int": 7, "wis": 11, "cha": 10}',
'{}',
'{"intimidation": 2}',
'{"darkvision": 60}',
'Common, Orc',
'[]', '[]', '[]',
'[{"name": "Aggressive", "description": "As a bonus action, the orc can move up to its speed toward a hostile creature that it can see."}]',
'[{"name": "Greataxe", "description": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage."}, {"name": "Javelin", "description": "Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 6 (1d6 + 3) piercing damage."}]',
2),

-- CR 1
('Bugbear', 'humanoid', 'medium', 'chaotic evil', 1, 16, 27, '5d8+5',
'{"walk": 30}',
'{"str": 15, "dex": 14, "con": 13, "int": 8, "wis": 11, "cha": 9}',
'{}',
'{"stealth": 6, "survival": 2}',
'{"darkvision": 60}',
'Common, Goblin',
'[]', '[]', '[]',
'[{"name": "Brute", "description": "A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack)."}, {"name": "Surprise Attack", "description": "If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack."}]',
'[{"name": "Morningstar", "description": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage."}, {"name": "Javelin", "description": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 9 (2d6 + 2) piercing damage in melee or 5 (1d6 + 2) piercing damage at range."}]',
2),

-- CR 2
('Ogre', 'giant', 'large', 'chaotic evil', 2, 11, 59, '7d10+21',
'{"walk": 40}',
'{"str": 19, "dex": 8, "con": 16, "int": 5, "wis": 7, "cha": 7}',
'{}',
'{}',
'{"darkvision": 60}',
'Common, Giant',
'[]', '[]', '[]',
'[]',
'[{"name": "Greatclub", "description": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage."}, {"name": "Javelin", "description": "Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 11 (2d6 + 4) piercing damage."}]',
2),

-- CR 3
('Owlbear', 'monstrosity', 'large', 'unaligned', 3, 13, 59, '7d10+21',
'{"walk": 40}',
'{"str": 20, "dex": 12, "con": 17, "int": 3, "wis": 12, "cha": 7}',
'{}',
'{"perception": 3}',
'{"darkvision": 60}',
'—',
'[]', '[]', '[]',
'[{"name": "Keen Sight and Smell", "description": "The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell."}]',
'[{"name": "Multiattack", "description": "The owlbear makes two attacks: one with its beak and one with its claws."}, {"name": "Beak", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one creature. Hit: 10 (1d10 + 5) piercing damage."}, {"name": "Claws", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) slashing damage."}]',
2),

-- CR 5
('Troll', 'giant', 'large', 'chaotic evil', 5, 15, 84, '8d10+40',
'{"walk": 30}',
'{"str": 18, "dex": 13, "con": 20, "int": 7, "wis": 9, "cha": 7}',
'{}',
'{"perception": 2}',
'{"darkvision": 60}',
'Giant',
'[]', '[]', '["fire", "acid"]',
'[{"name": "Keen Smell", "description": "The troll has advantage on Wisdom (Perception) checks that rely on smell."}, {"name": "Regeneration", "description": "The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn''t function at the start of the troll''s next turn. The troll dies only if it starts its turn with 0 hit points and doesn''t regenerate."}]',
'[{"name": "Multiattack", "description": "The troll makes three attacks: one with its bite and two with its claws."}, {"name": "Bite", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage."}]',
3),

-- CR 10
('Young Red Dragon', 'dragon', 'large', 'chaotic evil', 10, 18, 178, '17d10+85',
'{"walk": 40, "climb": 40, "fly": 80}',
'{"str": 23, "dex": 10, "con": 21, "int": 14, "wis": 11, "cha": 19}',
'{"dex_save": 4, "con_save": 9, "wis_save": 4, "cha_save": 8}',
'{"perception": 8, "stealth": 4}',
'{"blindsight": 30, "darkvision": 120}',
'Common, Draconic',
'["fire"]', '[]', '[]',
'[]',
'[{"name": "Multiattack", "description": "The dragon makes three attacks: one with its bite and two with its claws."}, {"name": "Bite", "description": "Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 17 (2d10 + 6) piercing damage plus 3 (1d6) fire damage."}, {"name": "Claw", "description": "Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 13 (2d6 + 6) slashing damage."}, {"name": "Fire Breath (Recharge 5-6)", "description": "The dragon exhales fire in a 30-foot cone. Each creature in that area must make a DC 17 Dexterity saving throw, taking 56 (16d6) fire damage on a failed save, or half as much damage on a successful one."}]',
4);
